# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      FC: gfortran
      LIBACCESSOM2_ROOT: $GITHUB_WORKSPACE/libaccessom2
      OASIS_ROOT: $GITHUB_WORKSPACE/oasis3-mct/Linux

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code 
        uses: actions/checkout@v2
      
      # Checkout libaccessom2
      - name: Checkout OASIS3-mct
        uses: actions/checkout@v2
        with:
          repository: COSIMA/oasis3-mct
          path: oasis3-mct

      # Install dependencies
      - name: Install dependencies
        run: sudo apt-get install -y openmpi-bin libopenmpi-dev libopenmpi2 netcdf-bin libnetcdf-dev libnetcdff-dev libnetcdf13 

      # Compile libaccessom2
      - name: Compile OASIS3-mct
        run: cd $GITHUB_WORKSPACE/oasis3-mct && make ubuntu

      # Install libaccessom2
      - name: Install libaccessom2
        run: | 
          wget https://github.com/COSIMA/libaccessom2/releases/latest/download/binary_release.tar.gz
          tar -zxf binary_release.tar.gz

      # Runs a set of commands using the runners shell
      - name: Build 1 degree
        run: |
          echo Building 1 degree
          make
